[features]
seeds = false
skip-lint = false

[programs.devnet]
battleship_contract = "7bp83FtVLDPGsk2vMftjHUeyNYE7LKGFJJFh2iLE36br"

[programs.localnet]
battleship_contract = "7bp83FtVLDPGsk2vMftjHUeyNYE7LKGFJJFh2iLE36br"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/matt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
