[features]
seeds = false
skip-lint = false
[programs.devnet]
mancala = "27kjU1HDLsU1kYudhryKg95ji2earYkWunWdyYQhbJjM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/matt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
