[features]
seeds = false
skip-lint = false
[programs.devnet]
hangman = "GsMHDbJU6hZx3yF2adbsyrC5aBcjw4XbewJQbLKwtrBe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/matt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
